/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LeafService } from "../leaf.service";
import { LeafCreateInput } from "./LeafCreateInput";
import { Leaf } from "./Leaf";
import { LeafFindManyArgs } from "./LeafFindManyArgs";
import { LeafWhereUniqueInput } from "./LeafWhereUniqueInput";
import { LeafUpdateInput } from "./LeafUpdateInput";

export class LeafControllerBase {
  constructor(protected readonly service: LeafService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Leaf })
  async createLeaf(@common.Body() data: LeafCreateInput): Promise<Leaf> {
    return await this.service.createLeaf({
      data: data,
      select: {
        createdAt: true,
        id: true,
        positionX: true,
        positionY: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Leaf] })
  @ApiNestedQuery(LeafFindManyArgs)
  async leaves(@common.Req() request: Request): Promise<Leaf[]> {
    const args = plainToClass(LeafFindManyArgs, request.query);
    return this.service.leaves({
      ...args,
      select: {
        createdAt: true,
        id: true,
        positionX: true,
        positionY: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Leaf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async leaf(
    @common.Param() params: LeafWhereUniqueInput
  ): Promise<Leaf | null> {
    const result = await this.service.leaf({
      where: params,
      select: {
        createdAt: true,
        id: true,
        positionX: true,
        positionY: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Leaf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateLeaf(
    @common.Param() params: LeafWhereUniqueInput,
    @common.Body() data: LeafUpdateInput
  ): Promise<Leaf | null> {
    try {
      return await this.service.updateLeaf({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          positionX: true,
          positionY: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Leaf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteLeaf(
    @common.Param() params: LeafWhereUniqueInput
  ): Promise<Leaf | null> {
    try {
      return await this.service.deleteLeaf({
        where: params,
        select: {
          createdAt: true,
          id: true,
          positionX: true,
          positionY: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
